
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 23 10:20:22 VET 2014
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
	  public static final int TIMES = 23;
	  public static final int READ = 16;
	  public static final int OVER = 24;
	  public static final int LT = 20;
	  public static final int LTE = 29;
	  public static final int RT = 30;
	  public static final int RTE = 31;
	  public static final int DIF = 32;
	  public static final int LB = 33;
	  public static final int RB = 34;
	  public static final int ELSE = 4;
	  public static final int PLUS = 21;
	  public static final int RPAREN = 26;
	  public static final int THEN = 3;
	  public static final int SEMI = 27;
	  public static final int COLON = 28;
	  public static final int WHILE = 7;
	  public static final int END = 5;
	  public static final int IF = 2;
	  public static final int LPAREN = 25;
	  public static final int WRITE = 17;
	  public static final int ID = 12;
	  public static final int NUM = 13;
	  public static final int DO = 8;
	  public static final int INTEGER = 9;
	  public static final int BOOLEAN = 10;
	  public static final int FOR = 11;
	  public static final int TO = 12;
	  public static final int AND = 13;
	  public static final int OR = 14;
	  public static final int EOF = 0;
	  public static final int MINUS = 22;
	  public static final int error = 1;
	  public static final int UNTIL = 15;
	  public static final int ASSIGN = 18;
	  public static final int EQ = 19;
	  public static final int REPEAT = 6;
}

